import {Game} from "./game";

export const GAMES: Game[] = [
  {
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },
  {
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },{
    id: 1,
    name: 'Match for noobs',
    gameMode: '1v1 solo mid',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 2,
    rate: 1000,
  },
  {
    id: 2,
    name: 'Match for middle noobs',
    gameMode: 'random draft',
    players: 2,
    server: 'us west',
    locked: 0,
    maxPlayers: 4,
    rate: 2000,
  },
  {
    id: 3,
    name: 'Match for milords',
    gameMode: 'all pick',
    players: 1,
    server: 'us west',
    locked: 1,
    maxPlayers: 10,
    rate: 3000,
  },
]
