export const SERVERS = [
  'us west',
  'us wast',
  'europe west',
  'singapore',
  'dubai',
  'stockholm',
  'brazil',
  'austria',
  'australia',
  'south africa',
  'chile',
  'peru',
  'dota region argentina',
  'india',
  'japan',
  'taiwan',
]

export const GAMEMODES = [
  "All Pick",
  "Captains Mode",
  "Random Draft",
  "Single Draft",
  "All Random",
  "Reverse Captains Mode",
  "Mid Only Mode",
  "Least Played",
  "New Player Mode",
  "Captains Draft",
  "Ability Draft",
  "All Random Death Match",
  "1v1 Solo Mid",
  "Ranked All Pick",
  "Turbo",
]
